import { constants as httpConstants } from 'http2';

const {
  HTTP_STATUS_CREATED: CREATED_201,
  HTTP_STATUS_BAD_REQUEST: BAD_REQUEST_400,
  HTTP_STATUS_UNAUTHORIZED: UNAUTHORIZED_401,
  HTTP_STATUS_FORBIDDEN: FORBIDDEN_403,
  HTTP_STATUS_NOT_FOUND: NOT_FOUND_404,
  HTTP_STATUS_CONFLICT: CONFLICT_409,
  HTTP_STATUS_INTERNAL_SERVER_ERROR: INTERNAL_SERVER_ERROR_500,
} = httpConstants;

const SERVER_ERROR_MESSAGE = 'На сервере произошла ошибка';
const VALIDATION_ERROR_MESSAGE = 'Некорректные данные:';
const UNAUTHORIZED_ERROR_MESSAGE = 'С токеном что-то не так';
const BAD_REQUEST_INCORRECT_PARAMS_ERROR_MESSAGE =
  'Некорректный запрос. Значения параметров page и limit должны быть числом';
const NOT_FOUND_ERROR_MESSAGE = 'Ресурс не найден. Проверьте URL и метод запроса';

const INCORRECT_USERDATA_MESSAGE = 'Неправильные почта или пароль';
const CONFLICT_ERROR_MESSAGE = 'Пользователь с таким email уже зарегистрирован';
const LOGIN_MESSAGE = 'Успешная авторизация';
const LOGOUT_MESSAGE = 'Вы вышли из системы';
const USER_NOT_FOUND_ERROR_MESSAGE = 'Такого пользователя нет';
const CAST_INCORRECT_USERID_ERROR_MESSAGE = 'Некорректный Id пользователя';

const ADVERT_NOT_FOUND_ERROR_MESSAGE = 'Такого объявления нет';
const DELETE_ADVERT_MESSAGE = 'Объявление удалено';
const CAST_INCORRECT_ADVERTID_ERROR_MESSAGE = 'Некорректный Id объявления';

const ARCHIVE_NOT_FOUND_ERROR_MESSAGE = 'Такого архива нет';
const DELETE_ARCHIVE_MESSAGE = 'Архив удалён';
const CAST_INCORRECT_ARCHIVEID_ERROR_MESSAGE = 'Некорректный Id архива';

const MEMBER_NOT_FOUND_ERROR_MESSAGE = 'Такого члена жюри нет';
const DELETE_MEMBER_MESSAGE = 'Запись члена жюри удалена';
const CAST_INCORRECT_MEMBERID_ERROR_MESSAGE = 'Некорректный Id члена жюри';

const OLYMPDATA_NOT_FOUND_ERROR_MESSAGE = 'Таких данных олимпиады нет';
const DELETE_OLYMPDATA_MESSAGE = 'Данные олимпиады удалены';
const CAST_INCORRECT_OLYMPDATAID_ERROR_MESSAGE = 'Некорректный Id данных олимпиады';

const PREPMATERIAL_NOT_FOUND_ERROR_MESSAGE = 'Такого материала для подготовки нет';
const DELETE_PREPMATERIAL_MESSAGE = 'Материал для подготовки удалён';
const CAST_INCORRECT_PREPMATERIALID_ERROR_MESSAGE = 'Некорректный Id материала для подготовки';

const RESULT_NOT_FOUND_ERROR_MESSAGE = 'Такого результата нет';
const DELETE_RESULT_MESSAGE = 'Результат удален';
const CAST_INCORRECT_RESULTID_ERROR_MESSAGE = 'Некорректный Id результата';
const BAD_REUEST_INCORRECT_RESULTINDEX_ERROR_MESSAGE = 'Недопустимый индекс результата';

const dateRegex = /^(0[1-9]|[1-2][0-9]|3[0-1])\.(0[1-9]|1[0-2])\.\d{4}$/;
const urlRegEx = /https?:\/\/w{0,3}\.?[\w0-9-]{1,10}\.\w{2,3}[\w\d\-._~:/?#[\]@!$&'()*+,;=]{0,}/m;

export {
  INCORRECT_USERDATA_MESSAGE,
  CONFLICT_ERROR_MESSAGE,
  LOGIN_MESSAGE,
  LOGOUT_MESSAGE,
  USER_NOT_FOUND_ERROR_MESSAGE,
  CAST_INCORRECT_USERID_ERROR_MESSAGE,
  CREATED_201,
  BAD_REQUEST_400,
  UNAUTHORIZED_401,
  FORBIDDEN_403,
  NOT_FOUND_404,
  CONFLICT_409,
  INTERNAL_SERVER_ERROR_500,
  SERVER_ERROR_MESSAGE,
  UNAUTHORIZED_ERROR_MESSAGE,
  VALIDATION_ERROR_MESSAGE,
  BAD_REQUEST_INCORRECT_PARAMS_ERROR_MESSAGE,
  NOT_FOUND_ERROR_MESSAGE,
  ADVERT_NOT_FOUND_ERROR_MESSAGE,
  DELETE_ADVERT_MESSAGE,
  CAST_INCORRECT_ADVERTID_ERROR_MESSAGE,
  ARCHIVE_NOT_FOUND_ERROR_MESSAGE,
  DELETE_ARCHIVE_MESSAGE,
  CAST_INCORRECT_ARCHIVEID_ERROR_MESSAGE,
  OLYMPDATA_NOT_FOUND_ERROR_MESSAGE,
  DELETE_OLYMPDATA_MESSAGE,
  CAST_INCORRECT_OLYMPDATAID_ERROR_MESSAGE,
  MEMBER_NOT_FOUND_ERROR_MESSAGE,
  DELETE_MEMBER_MESSAGE,
  CAST_INCORRECT_MEMBERID_ERROR_MESSAGE,
  RESULT_NOT_FOUND_ERROR_MESSAGE,
  DELETE_RESULT_MESSAGE,
  CAST_INCORRECT_RESULTID_ERROR_MESSAGE,
  BAD_REUEST_INCORRECT_RESULTINDEX_ERROR_MESSAGE,
  PREPMATERIAL_NOT_FOUND_ERROR_MESSAGE,
  DELETE_PREPMATERIAL_MESSAGE,
  CAST_INCORRECT_PREPMATERIALID_ERROR_MESSAGE,
  dateRegex,
  urlRegEx,
};
